version: '3.8'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'

  app:
    image: 'freelancer:latest'
    build:
      context: .
    container_name: freelancer
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
        - "8080:8080"